nav:
  首页: /
  关于: /about/
  归档: /archives/
  演示: https://www.shididev.com/uniapp-sqhrms/
  GitHub: https://github.com/nszaaa3

projects_url: http://github.com/nszaaa3

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/nszaaa3
        twitter: /
        facebook: /
        linkedin: /
    post_count: 5
    highlight: lightcode

# keept it like this to add the root path (probably a bug)
root: ..

solar:
    # factor between 0 (fast), 1(normal), 2(very slow)
    speed: 1
    sun_image: /images/sun.png
    earth_image: /images/earth.png
    jupiter_image: /images/jupiter.png
    mars_image: /images/mars.png
    mercury_image: /images/mercury.png
    shadow_image: /images/shadow.png
    venus_image: /images/venus.png

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:



# nszaaa3.github.io

#
## Hexo Configuration
### Docs: https://hexo.io/docs/configuration.html
### Source: https://github.com/hexojs/hexo/
#
## Site
#title: Wryyyyy
#subtitle: ''
#description: ''
#keywords:
#author: Shidi
#language: zh
#timezone: ''
#
#
## URL
### Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
#url: https://nszaaa3.github.io/
#root: /
#permalink: :year/:month/:day/:title/
#permalink_defaults:
#pretty_urls:
#  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
#  trailing_html: true # Set to false to remove trailing '.html' from permalinks
#
## Directory
#source_dir: source
#public_dir: public
#tag_dir: tags
#archive_dir: archives
#category_dir: categories
#code_dir: downloads/code
#i18n_dir: :lang
#skip_render:
#
## Writing
#new_post_name: :title.md # File name of new posts
#default_layout: post
#titlecase: false # Transform title into titlecase
#external_link:
#  enable: true # Open external links in new tab
#  field: site # Apply to the whole site
#  exclude: ''
#filename_case: 0
#render_drafts: false
#post_asset_folder: false
#relative_link: false
#future: true
#highlight:
#  enable: true
#  line_number: true
#  auto_detect: false
#  tab_replace: ''
#  wrap: true
#  hljs: false
#prismjs:
#  enable: false
#  preprocess: true
#  line_number: true
#  tab_replace: ''
#
## Home page setting
## path: Root path for your blogs index page. (default = '')
## per_page: Posts displayed per page. (0 = disable pagination)
## order_by: Posts order. (Order by date descending by default)
#index_generator:
#  path: ''
#  per_page: 10
#  order_by: -date
#
## Category & Tag
#default_category: uncategorized
#category_map:
#tag_map:
#
## Metadata elements
### https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
#meta_generator: true
#
## Date / Time format
### Hexo uses Moment.js to parse and display date
### You can customize the date format as defined i
### http://momentjs.com/docs/#/displaying/format/
#date_format: YYYY-MM-DD
#time_format: HH:mm:ss
### updated_option supports 'mtime', 'date', 'empty'
#updated_option: 'mtime'
#
## Pagination
### Set per_page to 0 to disable pagination
#per_page: 10
#pagination_dir: page
#
## Include / Exclude file(s)
### include:/exclude: options only apply to the 'source/' folder
#include:
#exclude:
#ignore:
#
## Extensions
### Plugins: https://hexo.io/plugins/
### Themes: https://hexo.io/themes/
#theme: solar-theme-hexo
#
## Deployment
### Docs: https://hexo.io/docs/one-command-deployment
#deploy:
#  type: git
#  repo: git@github.com:nszaaa3/nszaaa3.github.io.git
#  branch: master
#  message: wryyyy

